from typing import Any


def start_all() -> None: ...


class Machine:
    def wait_for_unit(self, unit: str) -> None: ...
    def wait_for_open_port(self, port: int) -> None: ...
    def sleep(self, seconds: int) -> None: ...
    def succeed(self, command: str) -> str: ...
    def wait_until_succeeds(self, command: str, *, timeout: int = 30) -> str: ...


source: Machine
target1: Machine
target2: Machine