def start_all() -> None: ...


class Machine:
    def wait_for_unit(self, unit: str, *, timeout: int = 900) -> None: ...
    def wait_for_open_port(self, port: int, *, timeout: int = 900) -> None: ...
    def succeed(self, command: str) -> str: ...
    def wait_until_succeeds(self, command: str, *, timeout: int = 900) -> str: ...


host: Machine
